### ISSUE TITLE
Bug: Single quotes are inserted as `&#39;`

### ISSUE THREAD

**Issue by kolibril13** [Rickaym/plywood-gallery-for-vscode#6]
When clicking on "Header" in the function gallery, this happens:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/44469195/202677330-fa865da7-e977-47a1-9b38-3a7ca80a1cb9.png">

**Comment by Rickaym** [comment]
I believe this issue is within the gallery "Functions" 
https://github.com/kolibril13/plywood-gallery-functions/blob/main/gallery_assets/gallery_parameters.json#L73-L78

![image](https://user-images.githubusercontent.com/66440980/202727281-eb8923f7-0ce4-4ada-9196-59af44a5bfac.png)

**Comment by kolibril13** [comment]
Actually, this is on purpose, as can be seen here:

https://github.com/kolibril13/plywood-gallery/blob/ab4aaf9253778aac78e7f77aff5adaf27acd297b/plywood_gallery/plywood_tools.py#L93

When I would put the single quote instead of `&#39;` the JavaScript for the website would not work here:

https://github.com/kolibril13/plywood-gallery/blob/ab4aaf9253778aac78e7f77aff5adaf27acd297b/plywood_gallery/jinja2_template/template_index.html#L40

**Comment by lbirkert** [comment]
Is there any specific reason you are using .innerHTML over .innerText?

**Comment by kolibril13** [comment]
No, there is no specific reason.
What advantage would innerText have?

**Comment by lbirkert** [comment]
> No, there is no specific reason. What advantage would innerText have?

Like the name suggests, it inserts text as text and not as html. This should also be prefered because of cross site scripting and such.

**Comment by lbirkert** [comment]
For example, these will do different things
```js
// Will insert as text (=> you will see <p>Hello World</p>)
document.body.innerText = "<p>Hello world!</p>"
```
```js
// Will insert as html (=> you will see 'Hello World' as a paragraph element)
document.body.innerHTML = "<p>Hello world!</p>" 
```

**Comment by kolibril13** [comment]
Ah nice!
Then I need `document.body.innerText`, I will change that!

**Comment by lbirkert** [comment]
This should be fixed now. Can you close this issue?

**Comment by Rickaym** [comment]
Yep, thanks.

Ricky.
