### ISSUE TITLE
Extension does not open any more 

### ISSUE THREAD

**Issue by kolibril13** [Rickaym/plywood-gallery-for-vscode#7]
I've noted that last time I've opened VS Code, the extension does not open any more. I also tried re-installing the extension, without success. I still have the plywood options in the VS Code panel, but clicking on them has no effect. Any ideas why this might be the case?
A few weeks ago, it was still working in version 0.0.3, and I have no idea what I've changed since then.

![image](https://user-images.githubusercontent.com/44469195/210402404-6f0b7042-aeb0-4d77-9a99-d95ad4eeba3a.png)

this is the error message in the "extension host" log:
```
2023-01-03 10:05:15.707 [error] TypeError: Cannot read properties of undefined (reading 'isExternal')
    at y (/Users/jan-hendrik/.vscode/extensions/rickaym.plywood-gallery-0.0.3/dist/extension.js:1:58717)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by lbirkert** [comment]
> A few weeks ago, it was still working in version 0.0.3

Latest stable release is still on 0.0.3. There shouldn't really be anything that has changed.

**Comment by kolibril13** [comment]
Deleting the folder `/Users/jan-hendrik/.vscode/extensions/rickaym.plywood-gallery-0.0.3` and reinstalling the extension solved the problem :)
